// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are configured only for Android and iOS.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnt1cCwRai57pMSdS-XVRh1PLKtA_dCIY',
    appId: '1:1002424043359:android:8a8f655d7a5d49a61218ea',
    messagingSenderId: '1002424043359',
    projectId: 'laqta-16406',
    storageBucket: 'laqta-16406.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb2k5gZRFj7zQ6tmiq0s4us5okmmLg_ZU',
    appId: '1:1002424043359:ios:af42e23c1321b64a1218ea',
    messagingSenderId: '1002424043359',
    projectId: 'laqta-16406',
    storageBucket: 'laqta-16406.firebasestorage.app',
    iosClientId:
        '1002424043359-tk3l3hlv85uqrkf43uqqhcgfpfb7ntjc.apps.googleusercontent.com',
    iosBundleId: 'com.luqta.luqta',
  );
}
