// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are configured only for Android and iOS.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnt1cCwRai57pMSdS-XVRh1PLKtA_dCIY',
    appId: '1:1002424043359:android:1d756517be0408a91218ea',
    messagingSenderId: '1002424043359',
    projectId: 'laqta-16406',
    storageBucket: 'laqta-16406.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb2k5gZRFj7zQ6tmiq0s4us5okmmLg_ZU',
    appId: '1:1002424043359:ios:5ea4fb27afc272711218ea',
    messagingSenderId: '1002424043359',
    projectId: 'laqta-16406',
    storageBucket: 'laqta-16406.firebasestorage.app',
    androidClientId: '1002424043359-7789fsq4srhi7a6kr63hddr80otjl17l.apps.googleusercontent.com',
    iosClientId: '1002424043359-7tmde5l68i54fvc0en3c3o6hst5nobsd.apps.googleusercontent.com',
    iosBundleId: 'com.laqta.laqta',
  );

}
