// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// For production, pass these via environment variables:
/// - FIREBASE_ANDROID_API_KEY
/// - FIREBASE_IOS_API_KEY
/// - FIREBASE_PROJECT_ID
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are configured only for Android and iOS.',
        );
    }
  }

  static const String _defaultAndroidApiKey =
      'AIzaSyCnt1cCwRai57pMSdS-XVRh1PLKtA_dCIY';
  static const String _defaultIosApiKey =
      'AIzaSyDb2k5gZRFj7zQ6tmiq0s4us5okmmLg_ZU';
  static const String _defaultProjectId = 'laqta-16406';
  static const String _defaultMessagingSenderId = '1002424043359';

  static FirebaseOptions get android {
    return FirebaseOptions(
      apiKey: const String.fromEnvironment(
        'FIREBASE_ANDROID_API_KEY',
        defaultValue: _defaultAndroidApiKey,
      ),
      appId: const String.fromEnvironment(
        'FIREBASE_ANDROID_APP_ID',
        defaultValue: '1:1002424043359:android:1d756517be0408a91218ea',
      ),
      messagingSenderId: _defaultMessagingSenderId,
      projectId: _defaultProjectId,
    );
  }

  static FirebaseOptions get ios {
    return FirebaseOptions(
      apiKey: const String.fromEnvironment(
        'FIREBASE_IOS_API_KEY',
        defaultValue: _defaultIosApiKey,
      ),
      appId: const String.fromEnvironment(
        'FIREBASE_IOS_APP_ID',
        defaultValue: '1:1002424043359:ios:5ea4fb27afc272711218ea',
      ),
      messagingSenderId: _defaultMessagingSenderId,
      projectId: _defaultProjectId,
      androidClientId: const String.fromEnvironment(
        'FIREBASE_ANDROID_CLIENT_ID',
        defaultValue:
            '1002424043359-7789fsq4srhi7a6kr63hddr80otjl17l.apps.googleusercontent.com',
      ),
      iosClientId: const String.fromEnvironment(
        'FIREBASE_IOS_CLIENT_ID',
        defaultValue:
            '1002424043359-7tmde5l68i54fvc0en3c3o6hst5nobsd.apps.googleusercontent.com',
      ),
      iosBundleId: 'com.laqta.laqta',
    );
  }
}
